{% set version = "11.3.4" %}
{% set name = "ntl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.shoup.net/ntl/ntl-{{ version }}.tar.gz
  sha256: 2d93baa2a1c6c7477113dc71413dedf74bcc8d9477427c3d1097be68fa30be39

build:
  number: 0
  skip: true        # [win]
  track_features:
    - ntl
  run_exports:
    - ntl {{ version }}

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gf2x
    - gmp
  run:
    - gf2x
    - gmp

test:
  commands:
    - test -f $PREFIX/include/NTL/ZZ.h
    - test -f $PREFIX/lib/lib{{ name }}.a
    - test -f $PREFIX/lib/lib{{ name }}.so         # [linux]
    - test -f $PREFIX/lib/lib{{ name }}.dylib      # [osx]

about:
  home: http://www.shoup.net/ntl/
  doc_url: http://www.shoup.net/ntl/doc/tour.html
  license: LGPL v2+
  license_file: doc/copying.txt
  summary: A Library for doing Number Theory
  description: |
    NTL is a high-performance, portable C++ library providing data structures and algorithms for manipulating signed, arbitrary length integers, and for vectors, matrices, and polynomials over the integers and over finite fields.

extra:
  recipe-maintainers:
    - isuruf
