{% set version = "11.4.3" %}
{% set name = "ntl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.shoup.net/ntl/ntl-{{ version }}.tar.gz
  sha256: b7c1ccdc64840e6a24351eb4a1e68887d29974f03073a1941c906562c0b83ad2

build:
  number: 2
  skip: True    # [win and vc<14]
  run_exports:
    - ntl {{ version }}

requirements:
  build:
    - libtool               # [not win]
    - automake              # [not win]
    - make                  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake                 # [win]
  host:
    - gf2x
    - gmp                   # [not win]
    - pthreads-win32        # [win]

test:
  commands:
    - test -f $PREFIX/include/NTL/ZZ.h              # [linux or osx]
    - test -f $PREFIX/lib/lib{{ name }}.a           # [linux or osx]
    - test -f $PREFIX/lib/lib{{ name }}.so          # [linux]
    - test -f $PREFIX/lib/lib{{ name }}.dylib       # [osx]
    - if not exist %LIBRARY_BIN%\\ntl.dll exit 1    # [win]
    - if not exist %LIBRARY_INC%\\NTL\\ZZ.h exit 1  # [win]

about:
  home: http://www.shoup.net/ntl/
  doc_url: http://www.shoup.net/ntl/doc/tour.html
  license: LGPL-2.0-or-later
  license_file: doc/copying.txt
  summary: A Library for doing Number Theory
  description: |
    NTL is a high-performance, portable C++ library providing data structures and algorithms for manipulating signed, arbitrary length integers, and for vectors, matrices, and polynomials over the integers and over finite fields.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
