travis:
  secure:
    BINSTAR_TOKEN: fy7r3Blm+ZSUIUVfJAOTDEtUVyIT2NStYvL94bOAnJPoPsqhD4LYdZbPNZ5lKkqOGcAUbdk4yuh0WIibPKomXkaMUr9FHhy1bZ5eZ3h4D0wdIylkDFVoU7sFvMEucZWsC3jpNPM6ZRXqBIbOAdnI0br2085y9fG+VEp7GDnrFsjnvP4Vbnhk5q/rfXHeNoN5YjwS/LEhGQ/I5UmLuLVhVLgej2ehKBZKYQjRapFJ7mhl+j2qIjBun0vmUExNgzwd08xoK6I9zGE6YSR+Jy6gWlJ1y2kCLFuvIPD8iETKgHU8nyVpG+5ZjayaVl7HBmilrnXjKRj++fqkUFdQXp/nOnF7ACHwsUtJaJHak94vQTEy2a4Dp+Bpl+UDh2d2HX2dwDQmsmllFzNiGt01aFyjAJWRQV5D51zQk1OR7gTKPBIZc/IbiTQqGwW8PRhK+2NRp1WIXtBeb80cPphELnP1cM87LfAn7hzwby3rAoFK9XvqZhGWKBgKAsyRPuCWqTCxrEpbjCwgkm/zYoH6TkvfcvDu9sh0Xrc83hFdK+n12gZfpqz6HzlDEFWBEGY5Y3NbyToJExW9ZBMs+cZUGton7rbFeD0/Vh0bfuxH6vjx1Pm077O6mwZAP3ZRk2k5iu4IfnpY6G7VzPaFOhi3TL/QqqlhIoOlwhmDTY0vm0+LSvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
